name: wisata_app
description: A new Flutter project.
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Poppins
  #     fonts:
  #     - asset: assets/fonts/Poppins/Poppins-Black.ttf
  #         weight: 900
  #       - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
  #         weight: 900
  #         style: italic
  #       - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
  #         weight: 800
  #         style: italic
  #       - asset: assets/fonts/Poppins/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
  #         weight: 700
  #         style: italic
  #       - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
  #         weight: 600
  #         style: italic
  #       - asset: assets/fonts/Poppins/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets/fonts/Poppins/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins/Poppins-Italic.ttf
  #         weight: 400
  #         style: italic
  #       - asset: assets/fonts/Poppins/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
  #         weight: 300
  #         style: italic
  #       - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
  #         weight: 200
  #         style: italic
  #       - asset: assets/fonts/Poppins/Poppins-Thin.ttf
  #         weight: 100
  #       - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
  #         weight: 100
  #         style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
